- name: Linux things
  hosts: linux
  become_user: root
  tasks:
  tasks:

  - name: get installed server components
    shell: "systemctl -l --type service --all | grep -v not-found"
    register: installedcomp

  - name: return value
    debug: var=installedcomp.stdout_lines

  - name: get installed applications
    shell: apt list --installed
    register: installedapps

  - name: return value
    debug: var=installedapps.stdout_lines

  - name: get software to be run on boot
    shell: "systemctl list-unit-files | grep enabled"
    register: boot

  - name: return value
    debug: var=boot.stdout_lines
