-  hosts: linux_hosts
  gather_facts: no
  remote_user: user
  become: yes
  become_method: sudent
  become_user: student
  tasks:
  - name: return installed server components
    shell: "systemctl -l --type service --all | grep -v not-found"
    register: installedcomp

  - name: return value
    debug: var=installedcomp.stdout_lines

  - name: return installed applications
    shell: apt list --installed
    register: installedapps

  - name: return value
    debug: var=installedapps.stdout_lines

  - name: return software to be run on boot
    shell: "echo fix this"
    register: boot

  - name: return value
    debug: var=boot.stdout_lines

  - name: recent user logons
    shell: "cat /var/log/auth.log | grep 'session opened' | grep -v cron:session"
    register: logins

  - name: return value
    debug: var=logins.stdout_lines

  - name: running processes
    shell: "ps -aux"
    register: proc

  - name: return value
    debug: var=proc.stdout_lines

  - name: suspicous connections
    shell: "netstat -tulpan | grep -v 127.0.0.1 | grep -v 127.0.1.1"
    register: conn

  - name: return value
    debug: var=conn.stdout_lines
