---
- name: Windows things
  hosts: windows
  vars:
    ansible_port: 5985
    ansible_connection: winrm
    ansible_user: Administrator@auditlab.rit
    ansible_password: Password1
    ansible_winrm_transport: ntlm
    tasks:
  
       - name: Recent Windows Logons
         win_shell: "echo changme"
         register: logons

       - name: return value
         debug: var=logons.stdout_lines
  
        # don't have user id 
       - name: Windows Running Processes
         win_shell: "Get-CimInstance -Class Win32_Process | Select-Object ProcessId, ProcessName, ParentProcessId, Path"
         register: feat

       - name: return value
         debug: var=feat.stdout_lines
    
       - name: Windows Suspicious Connections
         win_shell: "netstat | findstr /V 'https' | findstr /V 'http'"
         register: connect

       - name: return value
         debug: var=connect.stdout_lines
    
- name: Linux things
  hosts: linux
  become_user: root
  tasks:
    
    - name: Recent Linux Logons
      shell: "last | grep -E 'Nov ( [0-9]|10)'"
      register: logs
      
    - name: Linux Login Return Value
      debug: var=logs.stdout_lines
      
      # don't have the path of process
    - name: Linux Running Processes
      shell: "ps -o pid,cmd,user,ppid"
      register: runproc
      
    - name: Linux Processes Return Value
      debug: var=runproc.stdout_lines
      
    - name: Linux Suspicious Connections
      shell: "netstat -nputw | grep -v '443' | grep -v '80' "  
      register: susp
      
    - name: Linux Connections Return Value
      debug: var=susp.stdout_lines
