- hosts: win_clients
  gather_facts: no
  tasks:
  
  - name: Running Processes
    win_shell: "Get-Process | Select-Object ProcessName, Id"
    register: feat

  - name: return value
    debug: var=feat.stdout_lines
