- hosts: win_clients
  gather_facts: no
  tasks:

    - name: Download OSQuery
      win_get_url: 
        url: "https://osquery-packages.s3.amazonaws.com/windows/osquery-2.11.2.msi"
        dest: "C:\\Windows\\Temp\\osquery.msi"

    - name: Install OSQuery
      win_msi:
        path: "C:\\Windows\\Temp\\osquery.msi"
        wait: yes