- hosts: win_clients
  gather_facts: no
  tasks:
  
  - name: Recent logons
    win_shell: "echo changme"
    register: logons

  - name: return value
    debug: var=logons.stdout_lines
  
  - name: Running Processes
    win_shell: "Get-CimInstance -Class Win32_Process | Select-Object ProcessId, ProcessName, ParentProcessId, Path"
    register: feat

  - name: return value
    debug: var=feat.stdout_lines
    
  - name: Get Connections
    win_shell: "netstat -bano"
    register: connect

  - name: return value
    debug: var=connect.stdout_lines
    
