- hosts: win_clients
  gather_facts: no
  tasks:
  
  - name: Server Components
    win_shell: "Get-Service | select name, displayname"
    register: feat

  - name: return value
    debug: var=feat.stdout_lines
 
  - name: Installed Programs
    win_shell: "Get-WmiObject -Class WIN32_Product"
    register: pro
  
  - name: return value
    debug: var=pro.stdout_lines

  - name: Startup Programs
    win_shell: "Get-WmiObject -Class Win32_StartupCommand"
    register: startpro

  - name: return value
    debug: var=startpro.stdout_lines

 
