- hosts: win_clients
  gather_facts: no
  tasks:
  
  - name: Installed Feature
    win_shell: "Get-WindowsFeature | select Name, Installed | where {$_.Installed -eq 'True'}"
    register: feat

  - name: return value
    debug: var=feat.stdout_lines
 
  - name: Installed Programs
    win_shell: "Get-WmiObject -Class WIN32_Product"
    register: pro
  
  - name: return value
    debug: var=pro.stdout_lines

  - name: Startup Programs
    win_shell: "Get-WmiObject -Class Win32_StartupCommand"
    register: startpro

  - name: return value
    debug: var=startpro.stdout_lines

  - name: Recent logons
    win_shell: "echo changme"
    register: logons

  - name: return value
    debug: var=logons.stdout_lines

  - name: Process View
    win_shell: "Get-Process"
    register: process

  - name: return value
    debug: var=process.stdout_lines

  - name: Get Connections
    win_shell: "netstat -bano"
    register: connect

  - name: return value
    debug: var=connect.stdout_lines