# This is a testo yaml file for audit lab 

---  
- name: Windows osquery
  hosts: windows
  gather_facts: no
  vars:
    ansible_port: 5985
    ansible_connection: winrm
    ansible_user: Administrator@auditlab.rit
    ansible_password: Password1
    #ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm

  tasks:
      - name: Download OSquery - Windows 
        win_get_url:
            url: "https://pkg.osquery.io/windows/osquery-4.0.2.msi"
            dest: "C:\\Windows\\Temp\\osquery.msi"

      - name: Installing
        win_package:
            path: "C:\\Windows\\Temp\\osquery.msi"

      - name: OSquery Check 
        win_shell: "C:\\ProgramData\\osquery\\osqueryi.exe 'select * from logged_in_users;'"
        register: output

      - debug: var=output.stdout_lines


- name: Linux osquery 
  hosts: linux
  become_user: root

  tasks:
      - name: Download OSquery - Linux
        shell: "wget https://pkg.osquery.io/linux/osquery-4.0.2_1.linux_x86_64.tar.gz -O /osquery.tar.gz"

      - name: Extracint OSquery - Linux
        shell: "tar -xzvf /osquery.tar.gz -C /"
